build:
  version: "1.4"

accounts:
  message: "Welcome to EazyBank accounts related webhook APIs "
  contactDetails:
    name: "CR7 - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
